### ISSUE TITLE
Feature: VSCode support

### ISSUE THREAD

**Issue by borgdylan** [dotnet/ProjFileTools#11]
Will there there ever be a VSCode version of this? If yes would it support any msbuild project that uses the new Sdks feature in MSBuild? I am aware of omnisharp wanting to use this as its basis for csproj support.

**Comment by tintoy** [comment]
Hi .

I recently built [a VSCode extension](https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools) for `PackageReference` completions, but it doesn't use `ProjFileTools` (yet) because it's currently pure Typescript.

ProjectFileTools team - do you folks mind if I use this library in my extension? I'm in the process of [building a language server](https://github.com/tintoy/msbuild-project-tools-vscode/issues/2) so I'm now in a position to implement the core of the completion provider in managed code. It looks like you guys have expended a fair bit of effort making sure your implementation is correct so I'd rather not double up on the effort :)

**Comment by tintoy** [comment]
(I can't find the package on NuGet, which is why I'm asking if it's OK to reuse)

**Comment by mlorbetske** [comment]
By all means @tintoy. We haven't quite finished the work on the build process to get this publishing to NuGet as well, but if you'd like to build from source, that should be fine.

**Comment by tintoy** [comment]
@mlorbetske - I think I've wound up [a fair bit more](https://github.com/tintoy/msbuild-project-tools-vscode/raw/master/docs/images/extension-in-action.gif) functionality to my extension than ProjFileTools currently has, but I'm missing having that functionality when using Visual Studio.

I'd be happy to contribute some or all of the following functionality into your extension if you're interested:

* Tooltips to show evaluated conditions
* Tooltips to show whether a given property or item group is being used (and details if so, otherwise why not)
* Parsing and highlighting of MSBuild expressions
* Tooltips for symbols in MSBuild expressions
* _Some_ completions for MSBuild expressions (this is a lot harder in VSCode than it would be in VS, I suspect)
* Go to definition for imports (regular or SDK-style)
* Go to symbol for most MSBuild objects in the open project file
* _Some_ go to symbol support for MSBuild objects in imported projects.
* Go to `nuget.org` page for package from `PackageReference` / `DotNetCliToolsReference` element.

**Comment by mlorbetske** [comment]
@tintoy we'd be happy to take any contributions you'd be willing to make :)

**Comment by tintoy** [comment]
Awesome - I'll open a separate issue where we can discuss which components and features are a good fit for your vision of the extension :D

**Comment by tintoy** [comment]
@mlorbetske have you seen this?

https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension

Just as I was about to get around to [updating my sample](https://github.com/tintoy/dotnet-language-client/tree/master/samples/VisualStudioExtension) (now that the full framework no longer requires binding-redirects with stuff built against .NET Standard) it turns out they've built a fairly complete library for doing the same thing!

This might be a simpler way to surface functionality, what do you think?

**Comment by mlorbetske** [comment]
It looks good, I'd have to dig in a bit more before forming a strong opinion on the matter. Hopefully soon I'll have a bit of time to try it out.

**Comment by tintoy** [comment]
Oh, and it turns out that one of the people who worked on MonoDevelop built something very similar for VS 4 Mac that might be easier to port than mine is (and feature set looks to be pretty much the same as mine) so that might be even less work to integrate. I'll see if I can dig up a link when I get back from holiday.

**Comment by tintoy** [comment]
(I'm happy either way as long as VS gets the features I want for working with MSBuild projects 😉)

**Comment by mlorbetske** [comment]
Finally getting around to looking at the LSP information (sorry for the long delay). The LSP server side of things looks doable, having to shim the events into our overlay on the VS XML editor doesn’t seem like it’ll be the easiest task. Beyond that, we do rely on some services from the XML editor (like schema based completions for elements) that we’d need to rationalize with results from the LSP interactions. So I’m thinking probably not on the building an LSP client/server piece here.

I tried out @tintoy’s VS Code extension as well & it’s really good (feel free to post some extra info about it on this thread). With that in mind, I think the right answer here - for now at least - is to use that extension for project file editing enhancements in VS Code & for this repo to continue to build some of the things we can share across VS, VS Code and VS for Mac as well as the extension for VS itself.

**Comment by tintoy** [comment]
Thanks! Glad you liked it :)

I'm more than happy to collaborate if there is functionality worth sharing BTW. Otherwise all good on this end.
